generator:
  class: sfPropelGenerator
  param:
    model_class:           Student
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Student
    plural:                Students
    route_prefix:          student
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Lista de estudiantes
        layout: stacked
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
