<?php
// auto-generated by sfPropelAdmin
// date: 2008/03/28 22:29:39
?>
<div class="header icon-48-product">
<?php echo __('User') ?>: <?php if ($sf_guard_user->getId()): ?>[<?php echo __(' editing - ').' '.$sf_guard_user->getUsername() ?> ]<?php else: ?>[<?php echo __('create') ?>]<?php endif; ?>
</div>