<?php
// auto-generated by sfPropelAdmin
// date: 2008/03/28 22:29:39
?>
<?php echo object_input_hidden_tag($sf_guard_user, 'getId') ?>
<?php echo input_hidden_tag('do_after', '') ?>

<div class="col50">

<fieldset class="adminform">

				<legend><?php echo __('User Details') ?></legend>
<table class="admintable">
<tbody>

<?php include_partial('sfguarduser_form', array('sf_guard_user' => $sf_guard_user, 'pass'=>$pass)) ?>

<?php if(!$pass): ?>
  <tr>
    <td width="100" class="key"><?php echo __('Blocked') ?>:</td>
    <td>
    <?php if ($sf_request->hasError('sf_guard_user_profile{block}')): ?>
      <?php echo form_error('sf_guard_user_profile{block}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = object_checkbox_tag($sf_guard_user_profile, 'getBlock', array (
    'control_name' => 'sf_guard_user_profile[block]',
     )); echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  <tr>
    <td width="100" class="key"><?php echo __('Is active') ?>:</td>
    <td>
    <?php if ($sf_request->hasError('sf_guard_user{is_active}')): ?>
      <?php echo form_error('sf_guard_user{is_active}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = object_checkbox_tag($sf_guard_user, 'getIsActive', array (
    'control_name' => 'sf_guard_user[is_active]',
  )); echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  </tbody>
  </table>
  </fieldset>
  </div>

  <div class="col50">

  <fieldset class="adminform">

          <legend><?php echo __('User Profile') ?></legend>
  <table class="admintable">
  <tbody>
  <tr>
    <td width="100" class="key"><?php echo __('First Name') ?>:</td>
    <td>
    <?php echo input_hidden_tag($sf_guard_user_profile->getId(), 'profile_id') ?>
    <?php if ($sf_request->hasError('sf_guard_user_profile{first_name}')): ?>
      <?php echo form_error('sf_guard_user_profile{first_name}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = object_input_tag($sf_guard_user_profile, 'getFirstName', array (
    'size' => 30,
    'control_name' => 'sf_guard_user_profile[first_name]',
     )); echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  <tr>
    <td width="100" class="key"><?php echo __('Last Name') ?>:</td>
    <td>
    <?php if ($sf_request->hasError('sf_guard_user_profile{last_name}')): ?>
      <?php echo form_error('sf_guard_user_profile{last_name}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = object_input_tag($sf_guard_user_profile, 'getLastName', array (
    'size' => 40,
    'control_name' => 'sf_guard_user_profile[last_name]',
     )); echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  <tr>
    <td width="100" class="key"><?php echo __('Position') ?>:</td>
    <td>
    <?php if ($sf_request->hasError('sf_guard_user_profile{possition}')): ?>
      <?php echo form_error('sf_guard_user_profile{possition}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = object_input_tag($sf_guard_user_profile, 'getPossition', array (
    'size' => 50,
    'control_name' => 'sf_guard_user_profile[possition]',
     )); echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  <tr>
    <td width="100" class="key"><?php echo __('Last Login') ?>:</td>
    <td>
    <?php if ($sf_request->hasError('sf_guard_user{last_login}')): ?>
      <?php echo form_error('sf_guard_user{last_login}', array('class' => 'form-error-msg')) ?>
    <?php endif; ?>

    <?php $value = ($sf_guard_user->getLastLogin() !== null && $sf_guard_user->getLastLogin() !== '') ? format_date($sf_guard_user->getLastLogin(), "f") : ''; echo $value ? $value : '&nbsp;' ?>
    </td>
  </tr>
  </tbody>
  </table>
  </fieldset>
  </div>

    <div class="clr"></div>

  <fieldset class="adminform">

          <legend><?php echo __('User - Dependence') ?></legend>
    <table class="admintable">
    <tbody>
    <tr>
      <td width="100" class="key"><?php echo __('Dependences') ?>:</td>
      <td>
      <?php if ($sf_request->hasError('sf_guard_user{dependences}')): ?>
        <?php echo form_error('sf_guard_user{dependences}', array('class' => 'form-error-msg')) ?>
      <?php endif; ?>

      <?php $value = my_object_admin_double_list($sf_guard_user_profile, 'getDependences', array (
      'unassociated_label' => 'Sin Asociar',
      'associated_label' => 'Asociadas',
      'through_class' => 'UsersDependence',
    ), 'sfGuardUser::getDoubleListActiveDependences'); echo $value ? $value : '&nbsp;' ?>
      </td>
    </tr>
    </tbody>
    </table>
  </fieldset>

  <fieldset class="adminform">

          <legend><?php echo __('User - Groups/Roles') ?></legend>
    <table class="admintable">
    <tbody>
    <tr>
      <td width="100" class="key"><?php echo __('Groups/Roles') ?>:</td>
      <td>
      <?php if ($sf_request->hasError('sf_guard_user{groups}')): ?>
        <?php echo form_error('sf_guard_user{groups}', array('class' => 'form-error-msg')) ?>
      <?php endif; ?>

      <?php $value = object_admin_double_list($sf_guard_user, 'getGroups', array (
      'control_name' => 'sf_guard_user[groups]',
      'unassociated_label' => 'Sin Asociar',
      'associated_label' => 'Asociados',
      'through_class' => 'sfGuardUserGroup',
    )); echo $value ? $value : '&nbsp;' ?>
      </td>
    </tr>
    </tbody>
    </table>
  </fieldset>
<?php else: ?>
  </tbody>
  </table>
  </fieldset>
  </div>
<?php endif; ?>
</form>	
