<?php
// auto-generated by sfPropelAdmin
// date: 2008/03/28 22:29:39
?>
<?php use_helper('Object') ?>
<?php echo form_tag('sfGuardUser/list', array('method' => 'get', 'name' => 'prodfilter')) ?>
<?php echo input_hidden_tag('filter', '') ?>
<table>
  <tr>
    <td style="width: 100%">
      <table>
				<tr>
					<td style="width: 100%">
						<?php echo __('Id') ?>:
						<?php echo input_tag('filters[id]', isset($filters['id']) ? $filters['id'] : null, array ('size' => 7,'title' => __('Filter by Id'),)) ?>

            <?php echo __('First Name') ?>:
            <?php echo object_select_tag(isset($filters['user_id']) ? $filters['user_id'] : null, null, array (
              'include_blank' => true,
              'related_class' => 'sfGuardUserProfile',
              'text_method' => '__toString',
              'peer_method' => 'getMakeSelectUser',
              'control_name' => 'filters[user_id]',
            )) ?>

            <?php echo __('User') ?>:
            <?php echo object_select_tag(isset($filters['user_name']) ? $filters['user_name'] : null, null, array (
              'include_blank' => true,
              'related_class' => 'sfGuardUserProfile',
              'text_method' => 'getUserName',
              'peer_method' => 'getUserName',
              'control_name' => 'filters[user_name]',
            )) ?>

						<?php echo __('Possition') ?>:
						<?php echo input_tag('filters[possition]', isset($filters['possition']) ? $filters['possition'] : null, array (
                'size' => NULL,'title' => __('Filter by Possition'),)) ?>

            <?php echo __('Blocked') ?>:
            <?php echo select_tag('filters[block]', options_for_select(array(1 => __('yes'), 0 => __('no')), isset($filters['active']) ? $filters['active'] : null, array ('include_custom' => __("yes or no"),)), array ()) ?>
          
					</td>
				</tr>
        <tr>
				  <td style="width: 100%">
            <?php echo __('Active') ?>:
            <?php echo select_tag('filters[is_active]', options_for_select(array(1 => __('yes'), 0 => __('no')), isset($filters['active']) ? $filters['is_active  '] : null, array ('include_custom' => __("yes or no"),)), array ()) ?>

            <?php echo __('Dependence') ?>:
						<?php echo object_select_tag(isset($filters['dependence_id']) ? $filters['dependence_id'] : null, null, array (
              'include_blank' => true,
              'related_class' => 'Dependence',
              'peer_method'     => 'getMakeSelectDependence',
              'text_method' => '__toString',
              'control_name' => 'filters[dependence_id]',
            )) ?>

            <?php echo __('Group') ?>:
						<?php echo object_select_tag(isset($filters['guard_group_id']) ? $filters['guard_group_id'] : null, null, array (
              'include_blank' => true,
              'related_class' => 'sfGuardGroup',
              'peer_method'     => 'doSelect',              
              'control_name' => 'filters[guard_group_id]',
            )) ?>
          </td>
				</tr>
				<tr>
				  <td style="width: 100%">
				  <?php echo __('Created at') ?>:
				  <?php echo input_date_range_tag('filters[created_at]', isset($filters['created_at']) ? $filters['created_at'] : null, array (
            'rich' => true, 'withtime' => false,  'calendar_button_img' => '/sf/sf_admin/images/date.png',)) ?>
          <?php echo __('Updated at') ?>:
          <?php echo input_date_range_tag('filters[updated_at]', isset($filters['updated_at']) ? $filters['updated_at'] : null, array (
            'rich' => true,  'withtime' => false,  'calendar_button_img' => '/sf/sf_admin/images/date.png',)) ?>
          </td>
        </tr>
			</table>
    </td>
    <td>
      <table class="toolbar">
        <tr>
          <td class="button" id="toolbar-filter">
          <a href="#" onclick="javascript: document.forms.prodfilter.filter.value='filtrar';document.forms.prodfilter.submit();" class="toolbar">
          <span class="icon-32-filter" title="<?php echo __('Filter') ?>">
          </span> <?php echo __('Filter') ?> </a>
        </td>
          <td class="button" id="toolbar-reset">
            <a href="/sfGuardUser/list?filter=filter" class="toolbar">
            <span class="icon-32-cancel" title="<?php echo __('Reset') ?>">
            </span> <?php echo __('Reset') ?> </a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</form>

