<?php
// auto-generated by sfPropelAdmin
// date: 2008/03/28 22:29:39
?>
<tfoot>
  <tr>
    <td colspan="15">
		  <del class="container">
		  	<div class="pagination">
		  		<?php echo pager_navigation($pager, 'sfGuardUser/list') ?>
			</div>
	</del>				
    </td>
  </tr>
</tfoot>  
<tbody>
<?php $k = 0 ?>
<?php foreach ($pager->getResults() as $sf_guard_user): ?>
<tr class="<?php echo "row$k"; ?>">
<?php include_partial('list_td_tabular', array('sf_guard_user' => $sf_guard_user)) ?>
<?php include_partial('list_td_actions', array('sf_guard_user' => $sf_guard_user)) ?>
  </tr>
<?php $k = 1 - $k ?>
<?php endforeach; ?>
</tbody>
