<?php


/**
 * This class defines the structure of the 'sch_deposit' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jan 20 11:49:22 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.student.map
 */
class DepositTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.student.map.DepositTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sch_deposit');
		$this->setPhpName('Deposit');
		$this->setClassname('Deposit');
		$this->setPackage('lib.model.student');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('ID_STATE', 'IdState', 'INTEGER', true, null, null);
		$this->addColumn('AMOUNT', 'Amount', 'FLOAT', false, null, null);
		$this->addColumn('DELETED_BY', 'DeletedBy', 'INTEGER', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('COMMENT', 'Comment', 'LONGVARCHAR', false, null, null);
		$this->addColumn('DISCOUNT', 'Discount', 'FLOAT', false, null, null);
		$this->addForeignKey('CASHIER_ID', 'CashierId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('CURRENCY_ID', 'CurrencyId', 'INTEGER', 'sch_currency', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfGuardUser', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('cashier_id' => 'id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('Currency', 'Currency', RelationMap::MANY_TO_ONE, array('currency_id' => 'id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('SalesDeposit', 'SalesDeposit', RelationMap::ONE_TO_MANY, array('id' => 'deposit_id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('AccountDeposit', 'AccountDeposit', RelationMap::ONE_TO_MANY, array('id' => 'deposit_id', ), 'CASCADE', 'RESTRICT');
    $this->addRelation('MovementCashboxDeposit', 'MovementCashboxDeposit', RelationMap::ONE_TO_MANY, array('id' => 'deposit_id', ), 'CASCADE', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // DepositTableMap
