<?php
class DataSource
{
   
   
   public static $PROVINCIAS = array(
         "" => "",
         "NO EXISTE EN CNPV 2001" => "NO EXISTE EN CNPV 2001",
         "ANDRES IBAÑEZ" => "ANDRES IBAÑEZ",
         "WARNES" => "WARNES",
         "VELASCO" => "VELASCO",
         "ICHILO" => "ICHILO",
         "CHIQUITOS" => "CHIQUITOS",
         "SARA" => "SARA",
         "CORDILLERA" => "CORDILLERA",
         "VALLEGRANDE" => "VALLEGRANDE",
         "FLORIDA" => "FLORIDA",
         "OBISPO SANTIESTEVAN" => "OBISPO SANTIESTEVAN",
         "ÑUFLO DE CHAVEZ" => "ÑUFLO DE CHAVEZ",
         "ANGEL SANDOVAL" => "ANGEL SANDOVAL",
         "MANUEL MARIA CABALLERO" => "MANUEL MARIA CABALLERO",
         "GERMAN BUSCH" => "GERMAN BUSCH",
         "GUARAYOS" => "GUARAYOS",
   );
   
   
   public static $MUNICIPIOS = array(
         "NO EXISTE EN CNPV 2001" => array(
               "NO EXISTE EN CNPV 2001" => "NO EXISTE EN CNPV 2001"
         ),
         "ANDRES IBAÑEZ" => array(
               "CAPITAL (SANTA CRUZ DE LA SIERRA)" => "CAPITAL (SANTA CRUZ DE LA SIERRA)",
               "PRIMERA SECCION (COTOCA)" => "PRIMERA SECCION (COTOCA)",
               "SEGUNDA SECCION (PORONGO)" => "SEGUNDA SECCION (PORONGO)",
               "TERCERA SECCION (LA GUARDIA)" => "TERCERA SECCION (LA GUARDIA)",
               "CUARTA SECCION (EL TORNO)" => "CUARTA SECCION (EL TORNO)",
         ),
         "WARNES" => array(
               "PRIMERA SECCION (WARNES)" => "PRIMERA SECCION (WARNES)",
               "SEGUNDA SECCION (OKINAWA UNO)" => "SEGUNDA SECCION (OKINAWA UNO)",
         ),
         "VELASCO" => array(
               "PRIMERA SECCION (SAN IGNACIO DE VELASCO)" => "PRIMERA SECCION (SAN IGNACIO DE VELASCO)",
               "SEGUNDA SECCION (SAN MIGUEL DE VELASCO)" => "SEGUNDA SECCION (SAN MIGUEL DE VELASCO)",
               "TERCERA SECCION (SAN RAFAEL)" => "TERCERA SECCION (SAN RAFAEL)",
         ),
         "ICHILO" => array(
               "PRIMERA SECCION (BUENA VISTA)" => "PRIMERA SECCION (BUENA VISTA)",
               "SEGUNDA SECCION (SAN CARLOS)" => "SEGUNDA SECCION (SAN CARLOS)",
               "TERCERA SECCION (YAPACANI)" => "TERCERA SECCION (YAPACANI)",
               "CUARTA SECCION (SAN JUAN)" => "CUARTA SECCION (SAN JUAN)",
         ),
         "CHIQUITOS" => array(
               "PRIMERA SECCION (SAN JOSE DE CHIQUITOS)" => "PRIMERA SECCION (SAN JOSE DE CHIQUITOS)",
               "SEGUNDA SECCION (PAILON)" => "SEGUNDA SECCION (PAILON)",
               "TERCERA SECCION (ROBORE)" => "TERCERA SECCION (ROBORE)",
         ),
         "SARA" => array(
               "PRIMERA SECCION (PORTACHUELO)" => "PRIMERA SECCION (PORTACHUELO)",
               "SEGUNDA SECCION (SANTA ROSA DEL SARA)" => "SEGUNDA SECCION (SANTA ROSA DEL SARA)",
               "TERCERA SECCION (COLPA BELGICA)" => "TERCERA SECCION (COLPA BELGICA)",
         ),
         "CORDILLERA" => array(
               "PRIMERA SECCION (LAGUNILLAS)" => "PRIMERA SECCION (LAGUNILLAS)",
               "SEGUNDA SECCION (CHARAGUA)" => "SEGUNDA SECCION (CHARAGUA)",
               "TERCERA SECCION (CABEZAS)" => "TERCERA SECCION (CABEZAS)",
               "CUARTA SECCION (CUEVO)" => "CUARTA SECCION (CUEVO)",
               "QUINTA SECCION (GUTIERREZ)" => "QUINTA SECCION (GUTIERREZ)",
               "SEXTA SECCION (CAMIRI)" => "SEXTA SECCION (CAMIRI)",
               "SEPTIMA SECCION (BOYUIBE)" => "SEPTIMA SECCION (BOYUIBE)",
         ),
         "VALLEGRANDE" => array(
               "PRIMERA SECCION (VALLEGRANDE)" => "PRIMERA SECCION (VALLEGRANDE)",
               "SEGUNDA SECCION (TRIGAL)" => "SEGUNDA SECCION (TRIGAL)",
               "TERCERA SECCION (MORO MORO)" => "TERCERA SECCION (MORO MORO)",
               "CUARTA SECCION (POSTRER VALLE)" => "CUARTA SECCION (POSTRER VALLE)",
               "QUINTA SECCION (PUCARA)" => "QUINTA SECCION (PUCARA)",
         ),
         "FLORIDA" => array(
               "PRIMERA SECCION (SAMAIPATA)" => "PRIMERA SECCION (SAMAIPATA)",
               "SEGUNDA SECCION PAMPA GRANDE()" => "SEGUNDA SECCION (PAMPA GRANDE)",
               "TERCERA SECCION (MAIRANA)" => "TERCERA SECCION (MAIRANA)",
               "CUARTA SECCION (QUIRUSILLAS)" => "CUARTA SECCION (QUIRUSILLAS)",
         ),
         "OBISPO SANTIESTEVAN" => array(
               "PRIMERA SECCION (MONTERO)" => "PRIMERA SECCION (MONTERO)",
               "SEGUNDA SECCION (GRAL. SAAVEDRA)" => "SEGUNDA SECCION (GRAL. SAAVEDRA)",
               "TERCERA SECCION (MINEROS)" => "TERCERA SECCION (MINEROS)",
               "CUARTA SECCION (FERNANDEZ ALONSO)" => "CUARTA SECCION (FERNANDEZ ALONSO)",
               "QUINTA SECCION (SAN PEDRO)" => "QUINTA SECCION (SAN PEDRO)",
         ),
         "ÑUFLO DE CHAVEZ" => array(
               "PRIMERA SECCION (CONCEPCION)" => "PRIMERA SECCION (CONCEPCION)",
               "SEGUNDA SECCION (SAN JAVIER)" => "SEGUNDA SECCION (SAN JAVIER)",
               "TERCERA SECCION (SAN RAMON)" => "TERCERA SECCION (SAN RAMON)",
               "CUARTA SECCION (SAN JULIAN)" => "CUARTA SECCION (SAN JULIAN)",
               "QUINTA SECCION (SAN ANTONIO DE LOMERIO)" => "QUINTA SECCION (SAN ANTONIO DE LOMERIO)",
               "SEXTA SECCION (CUATRO CAÑADAS)" => "SEXTA SECCION (CUATRO CAÑADAS)",
         ),
         "ANGEL SANDOVAL" => array(
               "PRIMERA SECCION (SAN MATIAS)" => "PRIMERA SECCION (SAN MATIAS)",
         ),
         "MANUEL MARIA CABALLERO" => array(
               "PRIMERA SECCION (COMARAPA)" => "PRIMERA SECCION (COMARAPA)",
               "SEGUNDA SECCION (SAIPINA)" => "SEGUNDA SECCION (SAIPINA)",
         ),
         "GERMAN BUSCH" => array(
               "PRIMERA SECCION (PUERTO SUAREZ)" => "PRIMERA SECCION (PUERTO SUAREZ)",
               "SEGUNDA SECCION (PUERTO QUIJARRO)" => "SEGUNDA SECCION (PUERTO QUIJARRO)",
               "TERCERA SECCION (CARMEN RIVERO TORREZ)" => "TERCERA SECCION (CARMEN RIVERO TORREZ)",
         ),
         "GUARAYOS" => array(
               "PRIMERA SECCION (ASCENION DE GUARAYOS)" => "PRIMERA SECCION (ASCENION DE GUARAYOS)",
               "SEGUNDA SECCION (URUBICHA)" => "SEGUNDA SECCION (URUBICHA)",
               "TERCERA SECCION (EL PUENTE)" => "TERCERA SECCION (EL PUENTE)",
         ),
   );
   
   
   public static $IDIOMAS = array(
         "NINGUNO" => "NINGUNO",
         "QUECHUA" => "QUECHUA",
         "AYMARA" => "AYMARA",
         "GUARANI" => "GUARANI",
         "ARAONA" => "ARAONA",
         "ARAWAK" => "ARAWAK",
         "AYOREO" => "AYOREO",
         "BAURE" => "BAURE",
         "KANICHANA" => "KANICHANA",
         "KAVINEÑO" => "KAVINEÑO",
         "KAYUBABA" => "KAYUBABA",
         "CHACOBO" => "CHACOBO",
         "CHAPACURA" => "CHAPACURA",
         "CHIMAN" => "CHIMAN",
         "CHIPAYA" => "CHIPAYA",
         "CHIQUITANO" => "CHIQUITANO",
         "CHIQUITO" => "CHIQUITO",
         "CHIRIGUANO" => "CHIRIGUANO",
         "ESE EJJA" => "ESE EJJA",
         "GUARASUG'WE" => "GUARASUG'WE",
         "GUARAYOS" => "GUARAYOS",
         "IRUITO" => "IRUITO",
         "ITONAMA" => "ITONAMA",
         "IZOZEÑO" => "IZOZEÑO",
         "JAQI" => "JAQI",
         "LECO" => "LECO",
         "MATACO MAKA" => "MATACO MAKA",
         "MATACO NOCTENE" => "MATACO NOCTENE",
         "MEXEÑO" => "MEXEÑO",
         "MORE O ITENEZ" => "MORE O ITENEZ",
         "MOSETEN" => "MOSETEN",
         "MOVIMA" => "MOVIMA",
         "MURATO" => "MURATO",
         "PAGUARA" => "PAGUARA",
         "PANO" => "PANO",
         "SORIONO" => "SORIONO",
         "TACANA" => "TACANA",
         "TAPIETE" => "TAPIETE",
         "TOROMONA" => "TOROMONA",
         "TUPIGUARANI" => "TUPIGUARANI",
         "URU" => "URU",
         "YAMINAHUA" => "YAMINAHUA",
         "YURAKARE" => "YURAKARE",
         "YUKI" => "YUKI",
         "ZAMUCO" => "ZAMUCO",
         "PUKINA(PUQUI)" => "PUKINA(PUQUI)",
         "TSIMANE" => "TSIMANE",
         "WEENHAYEK" => "WEENHAYEK",
         "CASTELLANO" => "CASTELLANO",
         "BESIRO" => "BESIRO",
         "RUSO" => "RUSO",
         "PORTUGUES" => "PORTUGUES",
         "INGLES" => "INGLES",
         "FRANCES" => "FRANCES",
         "ALEMAN" => "ALEMAN",
         "TRINITARIO" => "TRINITARIO",
         "JAPONES" => "JAPONES",
         "MACHINERI" => "MACHINERI",
         "LENGUA DE SEÑAS BOL." => "LENGUA DE SEÑAS BOL.",
         "OTRO IDIOMA" => "OTRO IDIOMA",
   );
   
   
   public static $GRADO_INSTRUCCION= array(
         "SIN DATO" => "SIN DATO",
         "NINGUNA" => "NINGUNA",
         "PRIMARIA" => "PRIMARIA",
         "SECUNDARIA" => "SECUNDARIA",
         "TECNICO MEDIO" => "TECNICO MEDIO",
         "TECNICO SUPERIOR" => "TECNICO SUPERIOR",
         "NORMALISTA" => "NORMALISTA",
         "LICENCIATURA" => "LICENCIATURA",
         "CARRERA MILITAR" => "CARRERA MILITAR",
         "POSTGRADO" => "POSTGRADO",
         "BACHILLER" => "BACHILLER",
         "UNIVERSITARIO" => "UNIVERSITARIO",
         "NO SABE/NO RESPONDE" => "NO SABE/NO RESPONDE",
	);
   
   public static $PARENTESTO = array(
         "SIN DATO" => "SIN DATO",
         "PADRE" => "PADRE",
         "ABUELO" => "ABUELO",
         "ABUELA" => "ABUELA",
         "TIO" => "TIO",
         "TIA" => "TIA",
         "HERMANO(A)" => "HERMANO(A)",
         "TUTOR(A)" => "TUTOR(A)",
         "PADRE/MADRE" => "PADRE/MADRE",
         "SOLO" => "SOLO",
   );
}