generator:
  class: sfPropelGenerator
  param:
    model_class:           NightAudit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              NightAudit
    plural:                NightAudits
    route_prefix:          night_audit_NightAudit
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
