default:
  http_metas:
    content-type: text/html

  metas:
    title:        Basic
    description:  Basic
    keywords:     basic
    language:     es
    robots:       index, follow

  has_layout:     true
  layout:         layout