<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_attribute_contract' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 22 00:54:45 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class AttributeContractPeer extends BaseAttributeContractPeer {

    /**
    *
    * @param Int $id_state
    * @param String $key
    * @param String $value
    * @param String $label
    * @param String $description
    * @param Int $contract_id
    * @param Attribute $attribute || null
    * @param PropelPDO $con
    * @return Attribute 
    */
   public static function saveAttributeContract($id_state, $key, $value, $label, $description, $contract_id, $attribute_contract = null, $con = null)
   {
      if(!is_object($attribute_contract))
      {
	 $attribute_contract = new AttributeContract();
	 
      }
      
      $attribute_contract->setIdState($id_state);
      $attribute_contract->setKey($key);
      $attribute_contract->setValue($value);
      $attribute_contract->setLabel($label);
      $attribute_contract->setDescription($description);
      $attribute_contract->setContractId($contract_id);
      $attribute_contract->save($con);
      
      return $attribute_contract;
   }
   
   
   /**
    *     
    * @param String $key
    * @param Int $person_id
    * @param Int $id_state || null
    * @return Attribute
    */
   public static function getAttributeByKeyAndContract($key, $contract_id, $id_state = null)
   {
       $criteria = new Criteria();
       $criteria->add(self::KEY, $key);
       $criteria->add(self::CONTRACT_ID, $contract_id);
       
       if($id_state)
       {
           $criteria->add(self::ID_STATE, $id_state);
       }
       
       return self::doSelectOne($criteria);
   }
   
} // AttributeContractPeer
