<?php


/**
 * Skeleton subclass for representing a row from the 'sch_business_entity' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 28 00:21:32 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class BusinessEntity extends BaseBusinessEntity {

  public function  __toString()
  {
    return $this->getName();
  }
  
   public function getHoraCierre()
  {
     $r = '';
     
     $hour = $this->getNightAuditHour();
     switch ($hour) {
	case 0:
	   $r = '00:00';
	   break;
	case 1:
	   $r = '01:00';
	   break;
	case 2:
	   $r = '02:00';
	   break;
	case 3:
	   $r = '03:00';
	   break;
	case 4:
	   $r = '04:00';
	   break;
	case 5:
	   $r = '05:00';
	   break;
	case 6:
	   $r = '06:00';
	   break;
	case 7:
	   $r = '07:00';
	   break;
	case 8:
	   $r = '08:00';
	   break;
	case 9:
	   $r = '09:00';
	   break;
	case 10:
	   $r = '10:00';
	   break;
	case 11:
	   $r = '11:00';
	   break;
	case 12:
	   $r = '12:00';
	   break;
	case 13:
	   $r = '13:00';
	   break;
	case 14:
	   $r = '14:00';
	   break;
	case 15:
	   $r = '15:00';
	   break;
	case 16:
	   $r = '16:00';
	   break;
	case 17:
	   $r = '17:00';
	   break;
	case 18:
	   $r = '18:00';
	   break;
	case 19:
	   $r = '19:00';
	   break;
	case 20:
	   $r = '20:00';
	   break;
	case 21:
	   $r = '21:00';
	   break;
	case 22:
	   $r = '22:00';
	   break;
	case 23:
	   $r = '23:00';
	   break;
     }
     
     
     return $r;
     
  }
  
} // BusinessEntity
