<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_currency_price' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 28 00:21:33 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class CurrencyPricePeer extends BaseCurrencyPricePeer {
   
   public static function saveCurrencyPrice($data, $currency_price = null,  $con = null)
   {
      if(!is_object($currency_price))
      {
	 $currency_price = new CurrencyPrice();
      }
      
      PropertySetter::set($currency_price, $data);
      
      $currency_price->save($con);
      
      return $currency_price;
   }

   public static function getAnotherAssetExchange($currency_id, $id_state, $currency_price_id)
   {
      $criteria = new Criteria();
      
      $criteria->add(self::CURRENCY_ID, $currency_id);
      $criteria->add(self::ID_STATE, $id_state);
      
      $criteria->add(self::ID, $currency_price_id, Criteria::NOT_EQUAL);
      
      return self::doSelectOne($criteria);      
   }
   
   public static function getActiveCurrencyPrice($currency_id)
   {
      $criteria = new Criteria();
      
      $criteria->add(self::CURRENCY_ID, $currency_id);
      $criteria->add(self::ID_STATE, 2);
      
      return self::doSelectOne($criteria);
   }
   
   public static function getCurrencyPriceA($currency_id)
   {
      $criteria = new Criteria();
      
      $criteria->add(self::CURRENCY_ID, $currency_id);      
      $criteria->add(self::ID_STATE, 2);// Activo
      
      return self::doSelectOne($criteria);
   }
   
} // CurrencyPricePeer
