<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_curso' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Sep 29 21:26:34 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class CursoPeer extends BaseCursoPeer {

  public static function getCursoArray($period_id = null, $not_empty = null)
  {
    $criteria = new Criteria();
    
    if($period_id)
    {
	 $criteria->addJoin(self::ID, GradePeer::CURSO_ID);
	 $criteria->addJoin(GradePeer::ID, ContractGradePeer::GRADE_ID);
	 $criteria->addJoin(ContractGradePeer::CONTRACT_ID, ContractPeer::ID);
	 $criteria->add(ContractPeer::PERIOD_ID, $period_id);
    }    
    
    $criteria->addGroupByColumn(self::ID);
    
    $cursos = self::doSelect($criteria);
    if($not_empty)
    {        
        $array_curso = array();
    } else {
        $array_curso = array(0 => '');
    }
    
    foreach ($cursos as $curso)
    {
	$array_curso[$curso->getId()] = (string) $curso->getName();
    }
 
    return $array_curso;
  }
  
} // CursoPeer
