<?php


/**
 * Skeleton subclass for representing a row from the 'sch_form_of_payment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 28 00:21:32 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class FormOfPayment extends BaseFormOfPayment {

} // FormOfPayment
