<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_movement_cashbox_transfer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec  6 04:53:20 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class MovementCashboxTransferPeer extends BaseMovementCashboxTransferPeer {
   
     public static function getFromCashbox($cashbox_id = null)
     {
	  $c = new Criteria();
	  $c->add(MovementCashboxPeer::CASHBOX_ID, $cashbox_id);
	  $c->addJoin(self::MOVEMENT_CASHBOX_ID, MovementCashboxPeer::ID);
	  $c->add(MovementCashboxPeer::SUM, 0, Criteria::NOT_EQUAL);
	  
	  $c->addDescendingOrderByColumn(self::ID);

	  return self::doSelect($c);
     }
     
     public static function saveMovementCashboxTransfer($transfer_id, $movement_cashbox_id, $movement_cashbox_transfer = null, $con = null)
     {
	 if(!is_object($movement_cashbox_transfer))
	 {
	    $movement_cashbox_transfer = new MovementCashboxTransfer();
	 }

	 $movement_cashbox_transfer->setTransferId($transfer_id);
	 $movement_cashbox_transfer->setMovementCashboxId($movement_cashbox_id);
	 $movement_cashbox_transfer->save($con);

	 return $movement_cashbox_transfer;
     }

} // MovementCashboxTransferPeer
