<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_person' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Sep  4 00:14:38 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class PersonPeer extends BasePersonPeer {
   
   /**
    *
    * @param Int $id_state
    * @param Person $person || null
    * @param PropelPDO $con 
    * @return Person 
    */
   public static function savePerson($id_state, $person = null, $con = null)
   {
      if(!is_object($person))
      {
	 $person = new Person();	 	 
      }
      
      $person->setIdState($id_state);
      $person->save($con);
      
      return $person;
   }
   
} // PersonPeer
