<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_timetable' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 12 01:53:16 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class TimetablePeer extends BaseTimetablePeer {

  
  /**
   *  Devuelve una lista con todos turnos disponibles, ya sea
   * para un periodo o todos en general
   * 
   * @param Int $period_id || null
   * @return array
   */
  public static function getTimeTableArray($period_id = null, $not_empty = null)
  {
    $criteria = new Criteria();
    
    if($period_id)
    {
	 $criteria->addJoin(self::ID, GradePeer::TIMETABLE_ID);
	 $criteria->addJoin(GradePeer::ID, ContractGradePeer::GRADE_ID);
	 $criteria->addJoin(ContractGradePeer::CONTRACT_ID, ContractPeer::ID);
	 $criteria->add(ContractPeer::PERIOD_ID, $period_id);
    }    
    
    $criteria->addGroupByColumn(self::ID);
    
    $timetables = self::doSelect($criteria);
    if($not_empty)
    {
        $time_table = array();
    } else {        
        $time_table = array(0 => '');
    }    
    
    foreach ($timetables as $timetable)
    {
	$time_table[$timetable->getId()] = (string) $timetable->getName();
    }
 
    return $time_table;
  }
  
   
} // TimetablePeer
