<?php


/**
 * Skeleton subclass for representing a row from the 'sch_transfer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Dec  6 04:53:20 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class Transfer extends BaseTransfer {

   public function getTypeName()
   {
      $text = '';
      $type = $this->getType();
      switch ($type)
      {
	 case 1:
	    $text = 'Deposito';
	    break;
	 case 2:
	    $text = 'Retiro';
	    break;
      }
      
      return $text;
   }
   
   public function getNameCashier()
   {
      return TransferPeer::getNameCashier($this->getId());
   }
   
   public function getAprobadoPor()
   {
      $sf_guard_user = sfGuardUserPeer::retrieveByPK($this->getUserId());
      
      return $sf_guard_user->getUsername();
   }
   
   public function getCurrencyByMovement()
   {
      $currency = '';
      $movement_cashbox = TransferPeer::getCurrencyByMovement($this->getId());
      
      if($movement_cashbox->getCurrencyPrice()->getCurrency()->getId() == 2)
      {
	$currency = $movement_cashbox->getCurrencyPrice()->getCurrency()->getName().' ('.$movement_cashbox->getCurrencyPrice()->getPurchase().')'; 
      } else {
	$currency = $movement_cashbox->getCurrencyPrice()->getCurrency()->getName(); 
      }
      
      return $currency;
   }
} // Transfer
