<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sch_type_tutor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Sep  4 00:14:38 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model.student
 */
class TypeTutorPeer extends BaseTypeTutorPeer {  
   
   /**
    *
    * @param String $name
    * @param Int $id_state
    * @return TypeTutor
    */
   public static function getTypeTutorByName($name, $id_state)
   {
      $criteria = new Criteria();
      $criteria->add(self::NAME, $name);      
      $criteria->add(self::ID_STATE, $id_state);
      
      return self::doSelectOne($criteria);
   }
   
   /**
    *
    * @param Int $id_state
    * @param String $name
    * @param String $description
    * @param TypeTutor $type_tutor || null
    * @param PropelPDO $con
    * @return TypeTutor 
    */
   public static function saveTypeTutor($id_state, $name, $description, $type_tutor = null, $con = null)
   {
       if(!is_object($type_tutor))
       {
           $type_tutor = new TypeTutor();           
       }
       
       $type_tutor->setIdState($id_state);
       $type_tutor->setName($name);
       $type_tutor->setDescription($description);
       $type_tutor->save($con);
       
       return $type_tutor;
   }
   
   
} // TypeTutorPeer
